kind: pipeline
name: default
type: docker

steps:
  - name: deploy
    image: docker.umputun.com/system/deploy-ci:master
    commands:
      - ssh umputun@remark42.com "cd /srv/remark-site && git pull && git submodule update --recursive --remote"
      - ssh umputun@remark42.com "cd /srv/remark-site && docker-compose build && docker-compose up"
    when:
      branch: master
      event: push

  - name: notify
    image: drillster/drone-email
    settings:
      host: smtp.mailgun.org
      username:
        from_secret: email_username
      password:
        from_secret: email_password
      from: drone@mg.umputun.dev
      recipients: [sys@umputun.dev]
    when:
      status: [changed, failure]
