baseURL = "https://remark42.com"
languageCode = "en-us"
title = "Remark42, commenting system"
disableKinds=["taxonomy", "taxonomyTerm", "RSS"]

[module]
  [[module.mounts]]
    source="content"
    target="content"
  [[module.mounts]]
    source="docs"
    target="content/docs"

[params]
  [params.docs]
    current="1.5"
  [params.docs.versions]
    "1.5" = "1.5"
    "latest" = "Latest (1.x)"

