baseURL = "https://remark42.com"
languageCode = "en-us"
title = "Remark42, commenting system"

[module]
[[module.imports]]
path="github.com/umputun/remark42"
[[module.imports.mounts]]
source="docs"
target="content/docs"
