version: '2'

services:
  remark42-site:
    build: .
    image: umputun/remark42-site:master
    container_name: 'remark42-site'
    hostname: 'remark42-site'
    ports:
      - '1313:1313'
    environment:
      - ENV=development
    volumes:
      - ./remark42/docs:/app/content/docs"
